messages:
  prefix: "<bold><red>U<white>L <red>Breweries</bold> <dark_gray>» "
  info-header: '<gray><st>+|✦</st>============<bold>[ <red>Brewery Info <gray>]</bold>============<st>✦|+</st>'
  list-header: '<gray><st>+|✦</st>============<bold>[ <red>All Breweries <gray>]</bold>============<st>✦|+</st>'
  footer: '<gray><st>+|✦</st>==================<st>+✦+</st><gray>==================<st>✦|+'
  help-command:
    - '<bold><red>United<white>Breweries'
    - '<yellow>/brewery help - <white>shows a list of all commands'
    - '<yellow>/brewery create <gold><name> - <white>Creates a new brewery <gray>(can be multiple words)'
    - '<yellow>/brewery slogan <gold><slogan> - <white>Sets your brewery''s slogan <gray>(can be multiple words)'
    - '<yellow>/brewery delete - <white>Deletes your current brewery, if it exists'
    - '<yellow>/brewery invite <gold><player> - <white>Invites a player to your brewery'
    - '<yellow>/brewery upgrade - <white>Upgrades your brewery to the next level (up to 5)'
    - '<yellow>/brewery kick <gold><player> - <white>Kicks a player from your brewery'
    - '<yellow>/brewery accept - <white>Accepts any incoming brewery join requests'
    - '<yellow>/brewery deny - <white>Denies any incoming brewery join requests'
    - '<yellow>/brewery leave - <white>Makes you leave from your current brewery'
  help-command-admin:
    - '<bold><red>United<white>Breweries <red>Administration'
    - '<yellow>/breweryadmin help:<white> shows a list of all commands'
    - '<yellow>/breweryadmin reload:<white> reloads the plugin configuration'
    - '<yellow>/breweryadmin clearslogan <gold><brewery>:<white> clears a brewery''s slogan'
    - '<yellow>/breweryadmin delete <gold><brewery>:<white> Deletes specified brewery completely'
    - '<yellow>/breweryadmin addmember <gold><member> <brewery>:<white> adds a member to a brewery'
    - '<yellow>/breweryadmin removemember <gold><member> <brewery>:<white> removes a member from a brewery'
  brewery-created: '<green>brewery <yellow><brewery></yellow> has been successfully created! You can set a slogan with <yellow>/brewery slogan!'
  brewery-deleted: '<green>brewery <yellow><brewery></yellow> has been successfully deleted!'
  brewery-already-exists: '<red>brewery <yellow><brewery></yellow> already exists!'
  brewery-does-not-exist: '<red>A brewery with that name does not exist!'
  in-a-brewery: '<red>You are member of <yellow><brewery></yellow>! Leave or delete it first before making a new brewery!'
  must-own-brewery: '<red>You must own a brewery to use this command!'
  must-have-brewery: '<red>You must be in a brewery to use this command!'
  must-delete-brewery: '<red>You cannot leave <yellow><brewery></yellow>! You can only delete it.'
  brewery-invite: '<red>You were invited to join <yellow><brewery></yellow>!<red> Use <green>/brewery accept</green> or <dark_red>/brewery deny</dark_red>!'
  no-requests: '<red>You do not have any invites!'
  brewery-leave: '<red>You left <yellow><brewery>!'
  brewery-join: '<green>You joined <yellow><brewery>!'
  brewery-join-sender: '<yellow><player><red> has joined your brewery!'
  brewery-deny: '<red>You denied <yellow><brewery>''s invite!'
  brewery-deny-sender: '<red><player><yellow> has denied your invite!'
  slogan-changed: '<green>Sucessfully changed the slogan of <yellow><brewery></yellow>! It will be printed on the next bottle you brew!'
  player-kicked: '<green>Successfully kicked &e<player> from &e<brewery>!'
  kicked-from-brewery: '<red>You have been kicked from <yellow><brewery>!'
  cannot-kick-self: '<red>You cannot kick yourself from <yellow><brewery>!'
  cannot-invite-self: '<red>You cannot invite yourself to <yellow><brewery>!'
  player-invited: '<red>Invite sent to player!'
  not-enough-to-upgrade: '<red>You don''t have enough money to upgrade your brewery! You need <gold><bold><amount> Gold</bold></gold>!'
  not-enough-money: '<red>You don''t have enough money to create a brewery! You need <gold><bold>10,000 Gold</bold></gold>!'
  must-specify-kicked-player: '<red>Player argument missing! Please use <yellow>/brewery kick <player>!'
  must-specify-invited-player: '<red>Player argument missing! Please use <yellow>/brewery invite <player>!'
  must-specify-brewery-name: '<red>brewery name required! Please use <yellow>/brewery create <name>'
  must-specify-slogan: '<red>You must specify the new slogan!'
  player-left-brewery: '<yellow><player><red> left your brewery!'
  invalid-player: '<red>A player with that name does not exist!'
  brewery-upgraded: '<yellow><brewery><red> has been upgraded to level <yellow><level>!'
  max-brewery-level: '<red>Your brewery has reached the max level!'
  player-in-brewery: '<yellow><player><red> is already in a brewery!'
