name: UnitedBrands
version: ${project.version}
main: org.unitedlands.brands.UnitedBrands
api-version: 1.18
depend: [ Brewery ]
authors: [ Maroon28 ]
description: Item branding feature for UnitedLands
softdepend:
  - PlaceholderAPI
commands:
  brewery:
    description: main brewery command
  breweryadmin:
    description: command used for administrating breweries
    permission: united.brands.admin