name: UnitedWars
version: '${project.version}'
main: org.unitedlands.wars.UnitedWars
api-version: 1.19
depend: [ Towny, UnitedPvP ]
softdepend: [ PlaceholderAPI, AngelChest ]
authors: [ Maroon28 ]
description: A plugin which hooks into EventWar to achieve custom war behaviour!
website: unitedlands.org
commands:
  nationwar:
    description: "Used to declare nation wars"
    usage: "/nationwar [scroll/declare]"
  townwar:
    description: "Used to declare town wars"
    usage: "/townwar [scroll/declare]"
  waradmin:
    description: Used by admins to manage wars
    permission: united.wars.admin
  surrender:
    description: Used to surrender from wars or accept surrender requests
  mercenary:
    description: Used to hire mercenaries to wars, or accept a mercenary request.